version: '3'

volumes:
  production-postgres-data: {}
  production-postgres-data-backups: {}
  production-caddy: {}
  production-static: {}
  production-media: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: ..
      dockerfile: ./docker/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}-production-django
    depends_on:
      - postgres
      - redis
    volumes:
      - production-static:/app/{{ cookiecutter.project_slug }}/static-root
      - production-media:/app/{{ cookiecutter.project_slug }}/media-root
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
      - .envs/.production/.redis
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: docker/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}-production-postgres
    volumes:
      - production-postgres-data:/var/lib/postgresql/data
      - production-postgres-data-backups:/backups
    env_file:
      - .envs/.production/.postgres

  caddy:
    build:
      context: ..
      dockerfile: docker/production/caddy/Dockerfile
    image: {{ cookiecutter.project_slug }}-production-caddy
    depends_on:
      - django
    volumes:
      - production-caddy:/data
      - production-static:/srv/static
      - production-media:/srv/media
    env_file:
      - .envs/.production/.caddy
      - .envs/.production/.react
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    build:
      context: ..
      dockerfile: docker/production/redis/Dockerfile
    image: {{ cookiecutter.project_slug }}-production-redis
    env_file:
      - .envs/.production/.redis
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}-production-celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}-production-celerybeat
    command: /start-celerybeat

  {%- endif %}
