apiVersion: extensions/v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}_django_service
spec:
  selector:
    deployment: {{ cookiecutter.project_slug }}_django
  ports:
  - name:
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
